// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEBAPIDAN;

#nullable disable

namespace WEBAPIDAN.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230310032110_ruteo")]
    partial class ruteo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEBAPIDAN.Entidades.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreMarca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TecladoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TecladoId");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("WEBAPIDAN.Entidades.Modelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TecladoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TecladoId");

                    b.ToTable("Modelos");
                });

            modelBuilder.Entity("WEBAPIDAN.Entidades.Teclado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<string>("TipoConexion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teclados");
                });

            modelBuilder.Entity("WEBAPIDAN.Entidades.Marca", b =>
                {
                    b.HasOne("WEBAPIDAN.Entidades.Teclado", null)
                        .WithMany("Marcas")
                        .HasForeignKey("TecladoId");
                });

            modelBuilder.Entity("WEBAPIDAN.Entidades.Modelo", b =>
                {
                    b.HasOne("WEBAPIDAN.Entidades.Teclado", null)
                        .WithMany("Modelos")
                        .HasForeignKey("TecladoId");
                });

            modelBuilder.Entity("WEBAPIDAN.Entidades.Teclado", b =>
                {
                    b.Navigation("Marcas");

                    b.Navigation("Modelos");
                });
#pragma warning restore 612, 618
        }
    }
}
